# SPDX-License-Identifier: MPL-2.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: ensure-spdx
        name: Ensure SPDX headers
        entry: python tools/ensure_spdx.py
        language: system
        pass_filenames: true
        files: .*
